POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "Roberto",
    "email": "roberto@gmail.com",
    "password": "roberto123"
}

### Login

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "roberto@gmail.com",
    "password": "roberto123"
}

### Login

GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 2|xaqAUASgYb9hEK76wrxKVYtx5oscHTTfhuf8KxdY8d82b023