GET http://127.0.0.1:8000/api/users
Accept: application/json
Authorization: Bearer 1|ovwOrrqzHAfsMLy1EgLFNtjpm7Z533XIibg2WdU8f7be477b
### Guardar usuario

POST http://127.0.0.1:8000/api/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|bgexbw4NQWLB6bNzGXW6PCFrlPyxyeKzMAR24q2o2bbb3513

{
    "name": "Juan",
    "email": "juan@email.com",
    "password": "juan54321"
}

### Mostrar usuario

GET http://127.0.0.1:8000/api/users/3
Accept: application/json
Authorization: Bearer 5|bgexbw4NQWLB6bNzGXW6PCFrlPyxyeKzMAR24q2o2bbb3513


### Modificar usuario

PUT http://127.0.0.1:8000/api/users/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|bgexbw4NQWLB6bNzGXW6PCFrlPyxyeKzMAR24q2o2bbb3513

{
    "name": "Juan Modificado",
    "email": "juan@email.com"
}


### Eliminar usuario

DELETE http://127.0.0.1:8000/api/users/2
Accept: application/json
Authorization: Bearer 5|bgexbw4NQWLB6bNzGXW6PCFrlPyxyeKzMAR24q2o2bbb3513